### ISSUE TITLE
Missing assets-backup.zip 

### ISSUE THREAD

**Issue by pritisolanki** [Enngage/kontent-data-manager#2]
### Brief bug description

Command : kdm --action=backup --environmentId=xxx --format=csv --itemsFilename=items-backup.zip --assetsFilename=assets-backup.zip

### Repro steps

> kdm --action=backup --environmentId=xxxx --format=csv --itemsFilename=backup.zip --assetsFilename=assets-backup.zip
### Exporting content items of types: [author, quote]
[fetch][contentItem][default]: Albert Einstein
[fetch][contentItem][default]: Mahatma Gandhi
[fetch][contentItem][default]: Ralph Waldo Emerson
[fetch][contentItem][default]: Bernard Quote
[fetch][contentItem][default]: Einstein Quote
[fetch][contentItem][default]: Einstein quote
[fetch][contentItem][default]: Einstein Quote
[fetch][contentItem][default]: Einstein quote
[fetch][contentItem][default]: Einstein Quote
[fetch][contentItem][default]: Einstein quuote
[fetch][contentItem][default]: Gandhi Quote
[fetch][contentItem][default]: Gandhi Quote
[fetch][contentItem][default]: Gandhi Quote
[fetch][contentItem][default]: Gandhi Quote
**### Assets export is disabled**
### Transforming '14' content items: [csv]
[zip][author.csv]: Adding to zip
[zip][quote.csv]: Adding to zip
### Zip successfully generated: [1.76KB]
[writeFs]: ./backup.zip

Also, I tried giving fetchAssetDetails=true, but it still does not create assets-backup.zip

### Expected behavior

assets-backup.zip is created along wth backup.zip

### Test environment

 - Platform/OS: Mac
 - Browser: CLI

**Comment by Enngage** [comment]
@pritisolanki thank you :) There was another setting 'exportAssets' which was used previous, but I've now removed it and it should now work with just setting the `assetsFileName`. Can you please update the package and try again? :)
